Description of bml_annot_filter
Home > bml > annot > bml_annot_filter.m
bml_annot_filter
PURPOSE
BML_ANNOT_FILTER returns the annots that intersect with the filter
SYNOPSIS
function filtered = bml_annot_filter(cfg, annot, filter_annot)
DESCRIPTION
 BML_ANNOT_FILTER returns the annots that intersect with the filter
 Use as
   filtered = bml_annot_filter(cfg, annot, filter_annot);
   filtered = bml_annot_filter(annot, filter_annot);
 The first argument cfg is a optional configuration structure, which can contain
 the following optional fields:
 cfg.overlap - double: fraction of overlap required for filter. Defauls to
         zero (i.e. "touch")
 cfg.description - string: description of output annotation
 annot, filter - annot tables with fields 'starts' and 'ends'.
        'filter' should have no overlapping annotations
 Returns an annotation table with the folloing variables:
CROSS-REFERENCE INFORMATION
This function calls:
bml_annot_consolidate BML_ANNOT_CONSOLIDATE returns a consolidated annotation table
bml_annot_intersect BML_ANNOT_INTERSECT returns the intersection of two annotation tables
bml_annot_table BML_ANNOT_TABLE transforms a table into an annotations table [internal]
bml_getopt BML_GETOPT gets the value from a configuration structure [internal]
This function is called by:
bml_annot2raw BML_ANNOT2RAW creates a ft_datatype_raw from and annotation table
bml_annot2spike BML_ANNOT2SPIKE creates a ft_datatype_spike structure from an annotation table
bml_load_epoched BML_LOAD_EPOCHED loads an epoched raw from one or more files
bml_mask BML_MASK creates a new raw file with the specified values masked
bml_sync_analog BML_SYNC_ANALOG time-aligns files based on a common analog sync channel
SOURCE CODE
function filtered = bml_annot_filter(cfg, annot, filter_annot)
% BML_ANNOT_FILTER returns the annots that intersect with the filter
%
% Use as
%   filtered = bml_annot_filter(cfg, annot, filter_annot);
%   filtered = bml_annot_filter(annot, filter_annot);
%
% The first argument cfg is a optional configuration structure, which can contain
% the following optional fields:
% cfg.overlap - double: fraction of overlap required for filter. Defauls to
%         zero (i.e. "touch")
% cfg.description - string: description of output annotation
%
% annot, filter - annot tables with fields 'starts' and 'ends'.
%        'filter' should have no overlapping annotations
%
% Returns an annotation table with the folloing variables:
if nargin == 2
  overlap = 0;
  filter_annot=bml_annot_table(annot,'filter_annot');
  annot=bml_annot_table(cfg);
elseif nargin == 3
  overlap = bml_getopt(cfg,'overlap',0);
  annot=bml_annot_table(annot);
  filter_annot=bml_annot_table(filter_annot,'filter_annot');
else
  error('use as bml_annot_filter(annot, filter_annot)');
end
annot.Properties.Description = 'annot';
if isempty(annot) %optimization for empty filess
  filtered = annot;
  return
end
if overlap==0 && height(filter_annot)==1 %optimization for single row touch
  filtered = annot(annot.starts < filter_annot.ends(1) & annot.ends > filter_annot.starts(1),:);
  return
end
intersect = bml_annot_intersect(annot,filter_annot(:,1:4));
if isempty(intersect)
  filtered = table();
  return
end
intersect = intersect(:,{'id','starts','ends','duration','annot_id'});
if overlap>0
  cfg=[];
  cfg.criterion = @(x) (length(unique(x.annot_id))==1);
  intersect = bml_annot_consolidate(cfg,intersect);
  intersect = intersect(:,{'annot_id','cons_duration'});
  intersect.Properties.VariableNames = {'id','annot_filter_intersect_duration'};
  annot_intersect=join(annot(ismember(annot.id,intersect.id),1:4),intersect);
  duration_ratio = annot_intersect.annot_filter_intersect_duration ./ annot_intersect.duration;
  annot_intersect=annot_intersect((duration_ratio >= overlap) | (isnan(duration_ratio)),:);
  filtered = bml_annot_table(annot(ismember(annot.id,annot_intersect.id),:));
else
  filtered = annot(ismember(annot.id,intersect.annot_id),:);
end