Description of bml_annot_table
Home > bml > annot > bml_annot_table.m
bml_annot_table
PURPOSE
BML_ANNOT_TABLE transforms a table into an annotations table [internal]
SYNOPSIS
function annot=bml_annot_table(x, description, x_var_name)
DESCRIPTION
 BML_ANNOT_TABLE transforms a table into an annotations table [internal]
 Use as
   annot=bml_annot_table(x)
   annot=bml_annot_table(x, description)
   annot=bml_annot_table(x, [], x_var_name)
 x - table: should contains 'starts' and 'ends' variables
 description - string: description of the annotation table
 x_var_name - string: name of the variable used for the annot table, as
     returned by inputname(). Usefull for anidated calls.
 returns a table with variables 'id', 'starts', 'ends' and any additonal
 variable present in x. Issues a error on inconsistent input.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bml_annot2raw BML_ANNOT2RAW creates a ft_datatype_raw from and annotation table
bml_annot2spike BML_ANNOT2SPIKE creates a ft_datatype_spike structure from an annotation table
bml_annot_calculate BML_ANNOT_CALCULATE calculate scalar values from specific annotations in
bml_annot_consolidate BML_ANNOT_CONSOLIDATE returns a consolidated annotation table
bml_annot_coverage BML_ANNOT_COVERAGE calculates the fraction of denominator (y) covered by
bml_annot_detect BML_ANNOT_DETECT identifies annotations thresholding an envelope signal
bml_annot_difference BML_ANNOT_DIFFERENCE returns the difference of two annotation tables
bml_annot_extend BML_ANNOT_EXTEND extends the annotation times
bml_annot_filter BML_ANNOT_FILTER returns the annots that intersect with the filter
bml_annot_intersect BML_ANNOT_INTERSECT returns the intersection of two annotation tables
bml_annot_left_join BML_ANNOT_LEFT_JOIN performs a left join operation on annnotation tables
bml_annot_match BML_ANNOT_MATCH matches a raw data object to a template
bml_annot_overlap BML_ANNOT_OVERLAP calculates overlapping segments between annotations
bml_annot_plot BML_ANNOT_PLOT plots an annotation table
bml_annot_read BML_ANNOT_READ reads an annotation table
bml_annot_rename BML_ANNOT_RENAME changes the names of columns
bml_annot_rowbind BML_ANNOT_ROWBIND binds tables by rows, conforming to first non-empty table
bml_annot_shadow BML_ANNOT_SHADOW creates annotations that 'shadow' the ones in annot
bml_annot_transfer BML_ANNOT_TRANSFER copies information of transfer to annot
bml_annot_union BML_ANNOT_UNION returns the union of two annotation tables
bml_annot_write BML_ANNOT_WRITE writes an annotation table
bml_coding2annot BML_CODING2ANNOT creates annotation table from CodingMatrix
bml_event2annot BML_EVENT2ANNOT creates a annot table from a events structure
bml_plexon2annot BML_PLEXON2ANNOT loads spike events from plexon file
bml_raw2annot BML_RAW2ANNOT creates an annotation table from a raw
bml_roi_table BML_ROI_TABLE transforms a table into an ROI table [internal]
bml_info_raw BML_INFO_RAW return a annot table with OS and header info of each raw file in a folder.
bml_load_continuous BML_LOAD_CONTINUOUS loads continuous raw from one or more files
bml_load_epoched BML_LOAD_EPOCHED loads an epoched raw from one or more files
bml_neuroomega_info_raw BML_NEUROOMEGA_INFO_RAW returns table with OS and header info of raw neuroomega.mat (.mpx) files.
bml_redefinetrial BML_REDEFINETRIAL creates new epoching from a raw object (not necessarily continuous)
bml_chunk_sessions BML_CHUNK_SESSIONS breaks up sessions into smaller chunks
bml_sync_analog BML_SYNC_ANALOG time-aligns files based on a common analog sync channel
bml_sync_audio_event bml_sync_audio_event synchronizes zoom audio files according to
bml_sync_neuroomega_event BML_SYNC_NEUROOMEGA_EVENT synchronizes neuroomega files based on events
bml_sync_sortnotes BML_SYNC_SORTNOTES
bml_sync_transfer_neuroomega_chantype BML_SYNC_TRANSFER_NEUROOMEGA_CHANTYPE transfer sync info from one chantype to another
bml_sync_transfer_trellis_filetype BML_SYNC_TRANSFER_TRELLIS_FILETYPE transfer sync info between trellis filetypes
bml_timealign_annot BML_TIMEALIGN_ANNOT aligns slave to master and returns the slave's delta t
SOURCE CODE
function annot=bml_annot_table(x, description, x_var_name)
% BML_ANNOT_TABLE transforms a table into an annotations table [internal]
%
% Use as
%   annot=bml_annot_table(x)
%   annot=bml_annot_table(x, description)
%   annot=bml_annot_table(x, [], x_var_name)
%
% x - table: should contains 'starts' and 'ends' variables
% description - string: description of the annotation table
% x_var_name - string: name of the variable used for the annot table, as
%     returned by inputname(). Usefull for anidated calls.
%
% returns a table with variables 'id', 'starts', 'ends' and any additonal
% variable present in x. Issues a error on inconsistent input.
if isempty(x)
  x=table();
end
if isnumeric(x)
  if size(x,1) < size(x,2)
    x = x';
  end
  x = table(x);
end
if iscell(x); x=cell2table(x); end
if isstruct(x); x=struct2table(x); end
if ~exist('description','var') || isempty(description)
  if isempty(x.Properties.Description)
    if exist('x_var_name','var')
      description=x_var_name;
    else
      description=inputname(1);
    end
  else
    description=x.Properties.Description;
  end
end
if iscellstr(description)
  if numel(description)==1
    description = description{1};
  else
    error('The Description property must be a character vector.');
  end
end
if isempty(x)
  annot=table();
  annot.Properties.Description = description;
  return
end
if ~ismember('starts',x.Properties.VariableNames)
  if width(x)<=2
    x.Properties.VariableNames(1)={'starts'};
  else
    error('x should have variable ''starts''');
  end
end
if iscell(x.starts)
    x.starts=cell2mat(x.starts);
end
% if(any(ismissing(x.starts)))
%   warning("starts contains nans");
% end
if ~ismember('ends',x.Properties.VariableNames)
  if width(x)==1
    x.ends = x.starts;
  elseif width(x)==2
    x.Properties.VariableNames(2)={'ends'};
  else
    error('x should have variable ''ends''');
  end
end
if iscell(x.ends)
    x.ends=cell2mat(x.ends);
end
% if(any(ismissing(x.ends)))
%   warning("ends contains nans");
% end
if ~ismember('id',x.Properties.VariableNames)
  x = sortrows(x,'starts');
  x = [table(transpose(1:height(x)),'VariableNames',{'id'}), x];
else
  if iscell(x.id)
    x.id=cell2mat(x.id);
  end
  if length(unique(x.id)) < height(x)
    error('inconsistent id variable')
  else
    x = sortrows(x,'id');
  end
end
if ismember('duration',x.Properties.VariableNames)
  x.duration = [];
end
x = [x, table(x.ends - x.starts,'VariableNames',{'duration'})];
annot = bml_annot_reorder_vars(x, {'id','starts','ends','duration'});
annot.Properties.Description = description;