%% Creates the html documentation folder doc/
% requires m2html in path (https://www.artefact.tk/software/matlab/m2html/)
% last run 2018.09.25
% update bml/README.md for doc to point to the correct commit. 

GIT_PATH = 'C:\MATLAB_external_libs';

cd(GIT_PATH)
%rmdir('bml/doc') 
m2html('mfiles',{'bml/bml_defaults.m','bml/annot','bml/io','bml/signal','bml/sync','bml/utils','bml/anat','bml/plot','bml/stat','bml/timefreq'},...
  'htmldir','bml/doc', 'global','on');

fid = fopen('bml/info.xml','wt');
fprintf(fid,[ ... 
'<productinfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="optional">\n'... 
'<?xml-stylesheet type="text/xsl"href="optional"?>\n'... 
'<matlabrelease>R2017b</matlabrelease>\n'... 
'<name>BML</name>\n'... 
'<type>toolbox</type>\n'... 
'<icon></icon>\n'... 
'<help_location>./doc</help_location>\n'... 
'</productinfo>\n'... 
]);
fclose(fid);

fid = fopen('bml/doc/helptoc.xml','wt');
fprintf(fid,[ ... 
'<?xml version="1.0" encoding="utf-8"?>\n'... 
'<toc version="2.0">\n'... 
'    <tocitem target="index.html">BML</tocitem>\n'... 
'</toc>\n'... 
]);
fclose(fid);   
    
builddocsearchdb([GIT_PATH '/bml/doc'])    
    
    
    
  


