Description of bml_idx2time
Home > bml > sync > bml_idx2time.m
bml_idx2time
PURPOSE
BML_IDX2TIME calculates samples midpoint times from a index vector and file coordinates
SYNOPSIS
function time=bml_idx2time(cfg, idx, skipFactor)
DESCRIPTION
 BML_IDX2TIME calculates samples midpoint times from a index vector and file coordinates
 Use as
   time=bml_idx2time(cfg, idx)
   time=bml_idx2time(cfg, idx, skipFactor)
 idx - numeric vector of indices to transform to time
 skipFactor - numeric, integer indicating skip factor as used by blackrock
     NPMK package. Defaults to 1.
 where cfg is a configuration structure or roi table
 cfg.t1
 cfg.s1
 cfg.t2
 cfg.s2
 cfg.nSamples - double: optional total number of samples in file
 if cfg has more than one row, (s1, s2) should be non-overlaping
CROSS-REFERENCE INFORMATION
This function calls:
bml_annot_overlap BML_ANNOT_OVERLAP calculates overlapping segments between annotations
bml_getopt BML_GETOPT gets the value from a configuration structure [internal]
This function is called by:
bml_annot2raw BML_ANNOT2RAW creates a raw of zeros with ones at annot times
bml_coding2annot BML_CODING2ANNOT creates annot table from CodingMatrix
bml_event2annot BML_EVENT2ANNOT creates a annot table from a events structure
bml_plexon2annot BML_PLEXON2ANNOT loads spike events from plexon file
bml_roi_confluence BML_ROI_CONFLUENCE expands entries in a roi table to cover all the file
bml_load_continuous BML_LOAD_CONTINUOUS loads continuous raw from one or more files
bml_event2raw BML_EVENT2RAW creates a raw of zeros with ones at event times
bml_pad BML_PAD returns a padded version of the raw (crops if necessary)
bml_sync_analog BML_SYNC_ANALOG time-aligns files based on a common analog sync channel
bml_sync_transfer_neuroomega_chantype BML_SYNC_TRANSFER_NEUROOMEGA_CHANTYPE transfer sync info from one chantype to another
bml_timewarp BML_TIMEWARP aligns and linearly warps slave to master
SOURCE CODE
function time=bml_idx2time(cfg, idx, skipFactor)
% BML_IDX2TIME calculates samples midpoint times from a index vector and file coordinates
%
% Use as
%   time=bml_idx2time(cfg, idx)
%   time=bml_idx2time(cfg, idx, skipFactor)
%
% idx - numeric vector of indices to transform to time
% skipFactor - numeric, integer indicating skip factor as used by blackrock
%     NPMK package. Defaults to 1.
%
% where cfg is a configuration structure or roi table
% cfg.t1
% cfg.s1
% cfg.t2
% cfg.s2
% cfg.nSamples - double: optional total number of samples in file
%
% if cfg has more than one row, (s1, s2) should be non-overlaping
pTT = 9; %pTT = pTimeTolerenace = - log10(timetol)
if nargin==2
  skipFactor=1;
elseif nargin==3
  skipFactor=round(skipFactor);
else
  error('unsupported call to bml_idx2time, see usage');
end
if istable(cfg)
  if height(cfg) > 1
    %dealing with split sync
    assert(isempty(bml_annot_overlap(cfg(:,{'s1','s2'}))),...
      "cfg table contains overlapping segments of samples");
    time = zeros(1,length(idx));
    for i=1:height(cfg)
      t1=round(cfg.t1(i),pTT);
      s1=cfg.s1(i);
      t2=round(cfg.t2(i),pTT);
      s2=cfg.s2(i);
      Fs=round((s2-s1)/round(t2-t1,pTT),pTT,'significat');
      if skipFactor > 1
        s1=ceil(s1/skipFactor);
        s2=floor(s2/skipFactor);
        t1=t1+(skipFactor-1)*0.5/Fs;
        t2=t2-(skipFactor-1)*0.5/Fs;
        Fs = round((s2-s1)/round(t2-t1,pTT),pTT,'significat');
      end
      idx_filt = idx>=s1 & idx<=s2;
      time(idx_filt) = double(idx(idx_filt))/Fs - 0.5/Fs + (s2*t1-t2*s1)/(s2-s1);
    end
    return
  end
  cfg=table2struct(cfg);
end
%dealing with simple sync
t1=round(bml_getopt(cfg,'t1'),pTT);
s1=bml_getopt(cfg,'s1');
t2=round(bml_getopt(cfg,'t2'),pTT);
s2=bml_getopt(cfg,'s2');
Fs = round((s2-s1)/round(t2-t1,pTT),pTT,'significant');
if skipFactor > 1
  s1=ceil(s1/skipFactor);
  s2=floor(s2/skipFactor);
  t1=t1+(skipFactor-1)*0.5/Fs;
  t2=t2-(skipFactor-1)*0.5/Fs;
  Fs = round((s2-s1)/round(t2-t1,pTT),pTT,'significant');
end
time = double(idx)/Fs - 0.5/Fs + (s2*t1-t2*s1)/(s2-s1);