Description of bml_crop_idx_valid
Home > bml > sync > bml_crop_idx_valid.m
bml_crop_idx_valid
PURPOSE
BML_CROP_IDX_VALID calculates valid sample indices for a time window and file coordinates
SYNOPSIS
function [starts_idx,ends_idx] = bml_crop_idx_valid(cfg, varargin)
DESCRIPTION
 BML_CROP_IDX_VALID calculates valid sample indices for a time window and file coordinates
 Same as BML_CROP_IDX but bounds the starts and ends sample to the 1 and
 nSample if necesarry
 Use as
   [starts_idx,ends_idx] = bml_crop_idx_valid(cfg)
   [starts_idx,ends_idx] = bml_crop_idx_valid(cfg, starts, ends)
   [starts_idx,ends_idx] = bml_crop_idx_valid(cfg, starts, [], samples)
   [starts_idx,ends_idx] = bml_crop_idx_valid(cfg, [], ends, samples)
 where cfg is a configuration structure or roi table row
 cfg.starts
 cfg.ends
 (cfg.samples)
 cfg.t1
 cfg.s1
 cfg.t2
 cfg.s2
 cfg.nSamples - double: total number of samples in file
 cfg.tol - double: tolerance. Defaults to 1e-3/Fs.
 if starts and ends are given (3 argument call) the values of cfg are
 ignored
CROSS-REFERENCE INFORMATION
This function calls:
bml_crop_idx BML_CROP_IDX calculates sample indices for a time window and file coordinates
bml_getopt BML_GETOPT gets the value from a configuration structure [internal]
This function is called by:
bml_annot2raw BML_ANNOT2RAW creates a raw of zeros with ones at annot times
bml_annot_detect BML_ANNOT_DETECT identifies annotations thresholding an envelope signal
bml_load_continuous BML_LOAD_CONTINUOUS loads continuous raw from one or more files
SOURCE CODE
function [starts_idx,ends_idx] = bml_crop_idx_valid(cfg, varargin)
% BML_CROP_IDX_VALID calculates valid sample indices for a time window and file coordinates
%
% Same as BML_CROP_IDX but bounds the starts and ends sample to the 1 and
% nSample if necesarry
%
% Use as
%   [starts_idx,ends_idx] = bml_crop_idx_valid(cfg)
%   [starts_idx,ends_idx] = bml_crop_idx_valid(cfg, starts, ends)
%   [starts_idx,ends_idx] = bml_crop_idx_valid(cfg, starts, [], samples)
%   [starts_idx,ends_idx] = bml_crop_idx_valid(cfg, [], ends, samples)
%
% where cfg is a configuration structure or roi table row
% cfg.starts
% cfg.ends
% (cfg.samples)
% cfg.t1
% cfg.s1
% cfg.t2
% cfg.s2
% cfg.nSamples - double: total number of samples in file
% cfg.tol - double: tolerance. Defaults to 1e-3/Fs.
%
% if starts and ends are given (3 argument call) the values of cfg are
% ignored
nSamples  = bml_getopt(cfg,'nSamples',[]);
assert(~isempty(nSamples),'cfg.nSamples required');
[starts_idx,ends_idx] = bml_crop_idx(cfg, varargin{:});
% bounding to begging and end of file
if starts_idx<1
  starts_idx=1;
elseif starts_idx>nSamples
   error('starts index exceeds number of samples in file');
end
if ends_idx>nSamples
  ends_idx=nSamples;
elseif ends_idx<=0
  error('ends index %i before first sample',ends_idx);
end