Description of bml_apply
Home > bml > signal > bml_apply.m
bml_apply
PURPOSE
BML_APPLY applies a function to the data of each trial
SYNOPSIS
function raw = bml_apply(fun, data, varargin)
DESCRIPTION
 BML_APPLY applies a function to the data of each trial
 Use as
   raw = bml_apply(fun, data)
   raw = bml_apply(fun, data, other, args, for, fun)
 data - FT_DATAYPE_RAW to which to apply the function fun
 fun - function to be applyed to the data
 returns a raw with modified trials.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bml_reference_average_electrodes BML_REREFERENCE applies re-referencing scheme to raw
bml_rereference BML_REREFERENCE applies re-referencing scheme to raw
bml_rereference2 BML_REREFERENCE applies re-referencing scheme to raw
bml_rereference_average_electrodes BML_REREFERENCE applies re-referencing scheme to raw
bml_rereference_laplacian BML_REREFERENCE applies re-referencing scheme to raw
bml_rereference_monopolar BML_REREFERENCE applies re-referencing scheme to raw
bml_rereference_white_average_electrodes BML_REREFERENCE applies re-referencing scheme to raw
SOURCE CODE
function raw = bml_apply(fun, data, varargin)
% BML_APPLY applies a function to the data of each trial
%
% Use as
%   raw = bml_apply(fun, data)
%   raw = bml_apply(fun, data, other, args, for, fun)
%
% data - FT_DATAYPE_RAW to which to apply the function fun
% fun - function to be applyed to the data
%
% returns a raw with modified trials.
if nargin==2
  for i=1:numel(data.trial)
    data.trial{i} = fun(data.trial{i});
  end
else
  for i=1:numel(data.trial)
    data.trial{i} = fun(data.trial{i},varargin{:});
  end
end
raw=data;