Description of bml_crop
Home > bml > signal > bml_crop.m
bml_crop
PURPOSE
BML_CROP returns a time-cropped raw [INTERNAL]
SYNOPSIS
function cropped = bml_crop(raw, starts, ends)
DESCRIPTION
 BML_CROP returns a time-cropped raw [INTERNAL]
 Use as
   croped = bml_crop(raw, starts, ends)
   croped = bml_crop(cfg, raw)
 raw - FT_DATATYPE_RAW data to be cropped
 starts - double array: time in seconds for begging of each trial
          length of starts should coincide with number of trials of raw
 ends - double array: time in seconds for the end of each trial
          length of ends should coincide with number of trials of raw
 This function was designed to crop continuous files and is mailny used as
 an internal function. Use BML_REDEFINETRIAL to re-epoch a RAW.
CROSS-REFERENCE INFORMATION
This function calls:
bml_crop_idx BML_CROP_IDX calculates sample indices for a time window and file coordinates
bml_raw2coord BML_RAW2COORD returns the time coordinated of the raw
bml_getopt BML_GETOPT gets the value from a configuration structure [internal]
This function is called by:
bml_conform_to BML_CONFORM_TO conforms a slave ft_datatype_raw to the master's time
bml_pad BML_PAD returns a padded version of the raw (crops if necessary)
bml_sync_check BML_SYNC_CHECK loads files in a synchronization roi table into praat
bml_timewarp BML_TIMEWARP aligns and linearly warps slave to master
SOURCE CODE
function cropped = bml_crop(raw, starts, ends)
% BML_CROP returns a time-cropped raw [INTERNAL]
%
% Use as
%   croped = bml_crop(raw, starts, ends)
%   croped = bml_crop(cfg, raw)
%
% raw - FT_DATATYPE_RAW data to be cropped
% starts - double array: time in seconds for begging of each trial
%          length of starts should coincide with number of trials of raw
% ends - double array: time in seconds for the end of each trial
%          length of ends should coincide with number of trials of raw
%
% This function was designed to crop continuous files and is mailny used as
% an internal function. Use BML_REDEFINETRIAL to re-epoch a RAW.
if nargin==2
  cfg=raw;
  raw=starts;
  if istable(cfg)
    starts = cfg.starts;
    ends = cfg.ends;
  elseif isstruct(cfg)
    starts = bml_getopt(cfg,'starts');
    ends = bml_getopt(cfg,'ends');
  end
elseif nargin~=3
  error('invalid use of bml_crop');
end
assert(length(starts)==numel(raw.trial),...
  "length of starts (%i) doesn't match number of trials (%i)",length(starts),numel(raw.trial));
assert(length(ends)==numel(raw.trial),...
  "length of ends (%i) doesn't match number of trials (%i)",length(ends),numel(raw.trial));
cropped=raw;
for i=1:numel(raw.trial)
  nSamples = length(raw.time{i});
  tc=bml_raw2coord(raw,i);
  [s,e]=bml_crop_idx(tc,starts(i),ends(i));
  assert(e>0,"cropping interval outside raw")
  assert(s<=nSamples,"cropping interval outside raw")
  if s < 1; s=1; end
  if e > nSamples; e = nSamples; end
  cropped.trial{i} = raw.trial{i}(:,s:e);
  cropped.time{i} = raw.time{i}(:,s:e);
  cropped.sampleinfo(i,:) = [s,e];
end