Description of bml_getopt
Home > bml > utils > bml_getopt.m
bml_getopt
PURPOSE
BML_GETOPT gets the value from a configuration structure [internal]
SYNOPSIS
function val = bml_getopt(opt, key, default, emptymeaningful)
DESCRIPTION
 BML_GETOPT gets the value from a configuration structure [internal]
 Use as
   val = bml_getopt(s, key, default, emptymeaningful)
 where the input values are
   s               = structure or cell-array
   key             = string
   default         = any valid MATLAB data type (optional, default = [])
   emptymeaningful = boolean value (optional, default = 0)
 If the key is present as field in the structure, or as key-value pair in the
 cell-array, the corresponding value will be returned.
 If the key is not present, bml_getopt will return the default, or an empty array
 when no default was specified.
 If the key is present but has an empty value, then the emptymeaningful flag
 specifies whether the empty value or the default value should be returned.
 If emptymeaningful==true, then the empty array will be returned.
 If emptymeaningful==false, then the specified default will be returned.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bml_annot2raw BML_ANNOT2RAW creates a raw of zeros with ones at annot times
bml_annot2spike BML_ANNOT2SPIKE creates a ft_datatype_spike structure from an annotation table
bml_annot_consolidate BML_ANNOT_CONSOLIDATE returns a consolidated annotation table
bml_annot_detect BML_ANNOT_DETECT identifies annotations thresholding an envelope signal
bml_annot_filter BML_ANNOT_FILTER returns the annots that intersect with the filter
bml_annot_intersect BML_ANNOT_INTERSECT returns the intersection of two annotation tables
bml_annot_overlap BML_ANNOT_OVERLAP calculates overlapping segments between annotations
bml_annot_plot BML_ANNOT_PLOT plots an annotation table
bml_annot_shadow BML_ANNOT_SHADOW creates annotations that 'shadow' the ones in annot
bml_annot_t0 BML_ANNOT_T0 changes the time reference of an annot table
bml_annot_transfer BML_ANNOT_TRANSFER copies information of transfer to annot
bml_coding2annot BML_CODING2ANNOT creates annot table from CodingMatrix
bml_event2annot BML_EVENT2ANNOT creates a annot table from a events structure
bml_plexon2annot BML_PLEXON2ANNOT loads spike events from plexon file
bml_roi_confluence BML_ROI_CONFLUENCE expands entries in a roi table to cover all the file
bml_info_file BML_INFO_FILE returns table with OS info of each file in a folder
bml_info_raw BML_INFO_RAW return a annot table with OS and header info of each raw file in a folder.
bml_load_continuous BML_LOAD_CONTINUOUS loads continuous raw from one or more files
bml_load_epoched BML_LOAD_EPOCHED loads an epoched raw from one or more files
bml_neuroomega_info_file BML_NEUROOMEGA_INFO_FILE returns table with OS info of each neuroomega.mat file in a folder
bml_neuroomega_info_raw BML_NEUROOMEGA_INFO_RAW returns table with OS and header info of raw neuroomega.mat (.mpx) files.
bml_read_event BML_READ_EVENT reads fieldtrip's event structures from files
bml_check_contiguity BML_CHECK_CONTIGUITY returns true if raws are time-contiguous
bml_coding2raw BML_CODING2RAW creates a raw from the audio in the Coding file
bml_definetrial BML_DEFINETRIAL transforms a continuous raw into a trialed raw
bml_envelope_binabs BML_ENVELOPE_BINABS Calculate envelope of a signal using the binabs method
bml_event2raw BML_EVENT2RAW creates a raw of zeros with ones at event times
bml_hstack BML_HSTACK concatenates multiple raw data structures by time
bml_pad BML_PAD returns a padded version of the raw (crops if necessary)
bml_redefinetrial BML_REDEFINETRIAL creates new epoching from a raw object (not necessarily continuous)
bml_reorder_channels BML_REORDER_CHANNELS changes the order of the channels of a raw
bml_rereference BML_REREFERENCE applies re-referencing scheme to raw
bml_crop BML_CROP returns a time-cropped raw [INTERNAL]
bml_crop_idx BML_CROP_IDX calculates sample indices for a time window and file coordinates
bml_crop_idx_valid BML_CROP_IDX_VALID calculates valid sample indices for a time window and file coordinates
bml_idx2time BML_IDX2TIME calculates samples midpoint times from a index vector and file coordinates
bml_roi2coord BML_ROI2COORD calculates raw coordinates for entries in roi
bml_sync_analog BML_SYNC_ANALOG time-aligns files based on a common analog sync channel
bml_sync_check BML_SYNC_CHECK loads files in a synchronization roi table into praat
bml_sync_consolidate BML_SYNC_CONSOLIDATE consolidates file synchronization chunks
bml_sync_neuroomega_event BML_SYNC_NEUROOMEGA_EVENT synchronizes neuroomega files based on events
bml_sync_transfer_neuroomega_chantype BML_SYNC_TRANSFER_NEUROOMEGA_CHANTYPE transfer sync info from one chantype to another
bml_sync_transfer_trellis_filetype BML_SYNC_TRANSFER_TRELLIS_FILETYPE transfer sync info between trellis filetypes
bml_time2idx BML_TIME2IDX calculates sample indices from a time vector and file coordinates
bml_timealign BML_TIMEALIGN aligns slave to master and returns the slave's delta t
bml_timealign_annot BML_TIMEALIGN_ANNOT aligns slave to master and returns the slave's delta t
bml_timewarp BML_TIMEWARP aligns and linearly warps slave to master
bml_getopt_single BML_GETOPT_SINGLE gets a single value from a configuration structure [internal]
SOURCE CODE
function val = bml_getopt(opt, key, default, emptymeaningful)
% BML_GETOPT gets the value from a configuration structure [internal]
%
% Use as
%   val = bml_getopt(s, key, default, emptymeaningful)
% where the input values are
%   s               = structure or cell-array
%   key             = string
%   default         = any valid MATLAB data type (optional, default = [])
%   emptymeaningful = boolean value (optional, default = 0)
%
% If the key is present as field in the structure, or as key-value pair in the
% cell-array, the corresponding value will be returned.
%
% If the key is not present, bml_getopt will return the default, or an empty array
% when no default was specified.
%
% If the key is present but has an empty value, then the emptymeaningful flag
% specifies whether the empty value or the default value should be returned.
% If emptymeaningful==true, then the empty array will be returned.
% If emptymeaningful==false, then the specified default will be returned.
% 2017.10.27 AB: adapted from fieldtrip
%
% Copyright (C) 2011-2012, Robert Oostenveld
%
% This file is part of FieldTrip, see http://www.fieldtriptoolbox.org
% for the documentation and details.
%
%    FieldTrip is free software: you can redistribute it and/or modify
%    it under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.
%
%    FieldTrip is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    along with FieldTrip. If not, see <http://www.gnu.org/licenses/>.
%
% $Id$
if nargin<3
  default = [];
end
if nargin < 4
  emptymeaningful = 0;
end
if isa(opt, 'struct') || isa(opt, 'config')
  % get the key-value from the structure
  fn = fieldnames(opt);
  if ~any(strcmp(key, fn))
    val = default;
  else
    val = opt.(key);
  end
elseif istable(opt)
  assert(height(opt)==1,'configuration tables should be a 1 row high');
  if ~any(strcmp(key, opt.Properties.VariableNames))
    val = default;
  else
    val = opt.(key);
    if iscell(val)
      val = val{:};
    end
  end
elseif isa(opt, 'cell')
  % get the key-value from the cell-array
  if mod(length(opt),2)
    error('optional input arguments should come in key-value pairs, i.e. there should be an even number');
  end
  % the 1st, 3rd, etc. contain the keys, the 2nd, 4th, etc. contain the values
  keys = opt(1:2:end);
  vals = opt(2:2:end);
  % the following may be faster than cellfun(@ischar, keys)
  valid = false(size(keys));
  for i=1:numel(keys)
    valid(i) = ischar(keys{i});
  end
  if ~all(valid)
    error('optional input arguments should come in key-value pairs, the optional input argument %d is invalid (should be a string)', i);
  end
  hit = find(strcmpi(key, keys));
  if isempty(hit)
    % the requested key was not found
    val = default;
  elseif length(hit)==1
    % the requested key was found
    val = vals{hit};
  else
    error('multiple input arguments with the same name');
  end
elseif isempty(opt)
  % no options are specified, return default
  val = default;
end % isstruct or iscell or isempty
if isempty(val) && ~isempty(default) && ~emptymeaningful
  % use the default value instead of the empty input that was specified:
  % this applies for example if you do functionname('key', []), where
  % the empty is meant to indicate that the user does not know or care
  % what the value is
  val = default;
end
%returning cell of char instead of strings for compatibility with fieldtrip
if isstring(val) || iscellstr(val) || ischar(val)
  val = cellstr(val);
end