Description of bml_getopt_single
Home > bml > utils > bml_getopt_single.m
bml_getopt_single
PURPOSE
BML_GETOPT_SINGLE gets a single value from a configuration structure [internal]
SYNOPSIS
function val = bml_getopt_single(varargin)
DESCRIPTION
 BML_GETOPT_SINGLE gets a single value from a configuration structure [internal]
CROSS-REFERENCE INFORMATION
This function calls:
bml_getopt BML_GETOPT gets the value from a configuration structure [internal]
This function is called by:
bml_annot_intersect BML_ANNOT_INTERSECT returns the intersection of two annotation tables
bml_annot_plot BML_ANNOT_PLOT plots an annotation table
bml_coding2annot BML_CODING2ANNOT creates annot table from CodingMatrix
bml_plexon2annot BML_PLEXON2ANNOT loads spike events from plexon file
bml_info_file BML_INFO_FILE returns table with OS info of each file in a folder
bml_load_continuous BML_LOAD_CONTINUOUS loads continuous raw from one or more files
bml_load_epoched BML_LOAD_EPOCHED loads an epoched raw from one or more files
bml_neuroomega_info_raw BML_NEUROOMEGA_INFO_RAW returns table with OS and header info of raw neuroomega.mat (.mpx) files.
bml_read_event BML_READ_EVENT reads fieldtrip's event structures from files
bml_read_header BML_READ_HEADER reads header of a file
bml_coding2raw BML_CODING2RAW creates a raw from the audio in the Coding file
bml_event2raw BML_EVENT2RAW creates a raw of zeros with ones at event times
bml_rereference BML_REREFERENCE applies re-referencing scheme to raw
bml_sync_analog BML_SYNC_ANALOG time-aligns files based on a common analog sync channel
bml_sync_check BML_SYNC_CHECK loads files in a synchronization roi table into praat
bml_sync_consolidate BML_SYNC_CONSOLIDATE consolidates file synchronization chunks
bml_sync_transfer_neuroomega_chantype BML_SYNC_TRANSFER_NEUROOMEGA_CHANTYPE transfer sync info from one chantype to another
bml_sync_transfer_trellis_filetype BML_SYNC_TRANSFER_TRELLIS_FILETYPE transfer sync info between trellis filetypes
SOURCE CODE
function val = bml_getopt_single(varargin)
% BML_GETOPT_SINGLE gets a single value from a configuration structure [internal]
val = bml_getopt(varargin{:});
if iscell(val)
  if numel(val)==1
    val=convertStringsToChars(val{1});
  else
    error('Several elements in configuratoin where one was expected');
  end
elseif isstring(val)
  val = convertStringsToChars(val);
end